% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{book}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage[]{natbib}
\bibliographystyle{apalike}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Análisis de Factores Asociados al Mercado Inmobiliario},
  pdfauthor={Juan Luis Castillo},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Análisis de Factores Asociados al Mercado Inmobiliario}
\author{Juan Luis Castillo}
\date{2026-08-09}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(dplyr)}

\FunctionTok{library}\NormalTok{(GGally)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"data/housing.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(data,}\AttributeTok{n=}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   longitude latitude housing_median_age total_rooms total_bedrooms population
## 1   -122.23    37.88                 41         880            129        322
## 2   -122.22    37.86                 21        7099           1106       2401
## 3   -122.24    37.85                 52        1467            190        496
## 4   -122.25    37.85                 52        1274            235        558
## 5   -122.25    37.85                 52        1627            280        565
##   households median_income median_house_value ocean_proximity
## 1        126        8.3252             452600        NEAR BAY
## 2       1138        8.3014             358500        NEAR BAY
## 3        177        7.2574             352100        NEAR BAY
## 4        219        5.6431             341300        NEAR BAY
## 5        259        3.8462             342200        NEAR BAY
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    20640 obs. of  10 variables:
##  $ longitude         : num  -122 -122 -122 -122 -122 ...
##  $ latitude          : num  37.9 37.9 37.9 37.9 37.9 ...
##  $ housing_median_age: num  41 21 52 52 52 52 52 52 42 52 ...
##  $ total_rooms       : num  880 7099 1467 1274 1627 ...
##  $ total_bedrooms    : num  129 1106 190 235 280 ...
##  $ population        : num  322 2401 496 558 565 ...
##  $ households        : num  126 1138 177 219 259 ...
##  $ median_income     : num  8.33 8.3 7.26 5.64 3.85 ...
##  $ median_house_value: num  452600 358500 352100 341300 342200 ...
##  $ ocean_proximity   : chr  "NEAR BAY" "NEAR BAY" "NEAR BAY" "NEAR BAY" ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
   \FunctionTok{summarise}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{everything}\NormalTok{(),}\SpecialCharTok{\textasciitilde{}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.)),}\AttributeTok{.names=}\StringTok{"NA\_\{.col\}"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   NA_longitude NA_latitude NA_housing_median_age NA_total_rooms
## 1            0           0                     0              0
##   NA_total_bedrooms NA_population NA_households NA_median_income
## 1               207             0             0                0
##   NA_median_house_value NA_ocean_proximity
## 1                     0                  0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}
    \FunctionTok{where}\NormalTok{(is.numeric),}
    \SpecialCharTok{\textasciitilde{}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.),}\FunctionTok{mean}\NormalTok{(.,}\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{),.)}
\NormalTok{  )) }\OtherTok{{-}\textgreater{}}\NormalTok{ df}
\end{Highlighting}
\end{Shaded}

verifiquemos si tiene datos faltantes

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
   \FunctionTok{summarise}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{everything}\NormalTok{(),}\SpecialCharTok{\textasciitilde{}} \FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(.)),}\AttributeTok{.names=}\StringTok{"NA\_\{.col\}"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   NA_longitude NA_latitude NA_housing_median_age NA_total_rooms
## 1            0           0                     0              0
##   NA_total_bedrooms NA_population NA_households NA_median_income
## 1                 0             0             0                0
##   NA_median_house_value NA_ocean_proximity
## 1                     0                  0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df}\SpecialCharTok{$}\NormalTok{ocean\_proximity }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{ocean\_proximity)}
\end{Highlighting}
\end{Shaded}

\section{Análisis Univariado}\label{anuxe1lisis-univariado}

\subsection{\texorpdfstring{Variable Dependiente: Valor Medio de las Viviendas (\texttt{median\_house\_value})}{Variable Dependiente: Valor Medio de las Viviendas (median\_house\_value)}}\label{variable-dependiente-valor-medio-de-las-viviendas-median_house_value}

A continuación, se presenta un resumen estadístico detallado y la distribución de la variable dependiente \texttt{median\_house\_value}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}  \FunctionTok{summarise}\NormalTok{ (}\AttributeTok{n=}\FunctionTok{length}\NormalTok{(median\_house\_value),}
                            \AttributeTok{media=}\FunctionTok{mean}\NormalTok{(median\_house\_value),}
                            \AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(median\_house\_value),}
                            \AttributeTok{mediana=}\FunctionTok{median}\NormalTok{(median\_house\_value),}
                            \AttributeTok{RIC=}\FunctionTok{IQR}\NormalTok{(median\_house\_value),}
                            \AttributeTok{q1=}\FunctionTok{quantile}\NormalTok{(median\_house\_value,}\FloatTok{0.25}\NormalTok{),}
                            \AttributeTok{q3=}\FunctionTok{quantile}\NormalTok{(median\_house\_value,}\FloatTok{0.75}\NormalTok{),}
                            \AttributeTok{minimo=}\FunctionTok{min}\NormalTok{(median\_house\_value),}
                            \AttributeTok{maximo=}\FunctionTok{max}\NormalTok{(median\_house\_value)}
\NormalTok{                            ) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       n    media       sd mediana    RIC     q1     q3 minimo maximo
## 1 20640 206855.8 115395.6  179700 145125 119600 264725  14999 500001
\end{verbatim}

\textbf{Interpretación Estadística:}
El conjunto de datos comprende un total de \(N = 20,640\) registros de bloques habitacionales en el estado de California. La variable respuesta de interés, \texttt{median\_house\_value} (valor medio de las viviendas), presenta una media muestral de \(\$206,855.8\) USD con una desviación estándar de \(\$115,395.6\) USD, lo que evidencia una notable dispersión en las cotizaciones inmobiliarias.

En cuanto a las medidas de posición:
- La mediana se sitúa en \(\$179,700\) USD, lo que indica que el \(50\%\) de los bloques residenciales posee un valor de vivienda igual o menor a este límite.
- El rango intercuartílico (RIC), comprendido entre el primer cuartil (\(Q_1 = \$119,600\) USD) y el tercer cuartil (\(Q_3 = \$264,725\) USD), confirma que la mitad central de las viviendas oscila dentro de este rango.
- Los valores extremos muestran un mínimo registrado de \(\$14,999\) USD y un máximo de \(\$500,001\) USD.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{median\_house\_value))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\FunctionTok{after\_stat}\NormalTok{(density)),}
                 \AttributeTok{binwidth=}\DecValTok{20000}\NormalTok{,}
                 \AttributeTok{fill=}\StringTok{"\#1f77b4"}\NormalTok{,}
                 \AttributeTok{color=}\StringTok{"white"}\NormalTok{,}
                 \AttributeTok{alpha=}\FloatTok{0.7}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color=}\StringTok{"\#d62728"}\NormalTok{, }\AttributeTok{linewidth=}\FloatTok{1.2}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Distribución del Valor Medio de las Viviendas\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Valor Medio de la Casa (USD)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Densidad\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/hist_dep-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\StringTok{""}\NormalTok{, }\AttributeTok{y=}\NormalTok{median\_house\_value))}\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{fill=}\StringTok{"\#1f77b4"}\NormalTok{, }\AttributeTok{color=}\StringTok{"black"}\NormalTok{, }\AttributeTok{outlier.color =} \StringTok{"\#d62728"}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.7}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{stat\_summary}\NormalTok{(}\AttributeTok{fun=}\NormalTok{mean, }\AttributeTok{geom=}\StringTok{\textquotesingle{}point\textquotesingle{}}\NormalTok{, }\AttributeTok{shape=}\DecValTok{23}\NormalTok{, }\AttributeTok{size=}\DecValTok{3}\NormalTok{, }\AttributeTok{fill=}\StringTok{"white"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Diagrama de Caja de la Variable Dependiente\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Valor Medio de la Casa (USD)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/box_dep-1} \end{center}

\textbf{Interpretación de la Distribución:}
La distribución de \texttt{median\_house\_value} exhibe un sesgo positivo (hacia la derecha). Además, se identifica una concentración atípica de frecuencias en el extremo superior de \(\$500,001\) USD. Este comportamiento en el histograma y el diagrama de caja denota un proceso de truncamiento o censura a la derecha en la recopilación de datos, donde las viviendas con valores iguales o superiores a dicho umbral fueron codificadas bajo el valor estandarizado de \(\$500,001\) USD.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Variables Independientes Numéricas}\label{variables-independientes-numuxe9ricas}

Evaluamos las características generales de los predictores cuantitativos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric),}\SpecialCharTok{{-}}\NormalTok{median\_house\_value) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{pivot\_longer}\NormalTok{(}
    \AttributeTok{cols=}\FunctionTok{everything}\NormalTok{(),}
    \AttributeTok{names\_to =} \StringTok{\textquotesingle{}variable\textquotesingle{}}\NormalTok{,}
    \AttributeTok{values\_to =} \StringTok{\textquotesingle{}valor\textquotesingle{}}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(variable) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{ (}\AttributeTok{n=}\FunctionTok{length}\NormalTok{(valor),}
             \AttributeTok{media=}\FunctionTok{mean}\NormalTok{(valor),}
             \AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(valor),}
             \AttributeTok{mediana=}\FunctionTok{median}\NormalTok{(valor),}
             \AttributeTok{RIC=}\FunctionTok{IQR}\NormalTok{(valor),}
             \AttributeTok{q1=}\FunctionTok{quantile}\NormalTok{(valor,}\FloatTok{0.25}\NormalTok{),}
             \AttributeTok{q3=}\FunctionTok{quantile}\NormalTok{(valor,}\FloatTok{0.75}\NormalTok{),}
             \AttributeTok{minimo=}\FunctionTok{min}\NormalTok{(valor),}
             \AttributeTok{maximo=}\FunctionTok{max}\NormalTok{(valor)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 8 x 10
##   variable      n   media     sd mediana    RIC      q1      q3   minimo  maximo
##   <chr>     <int>   <dbl>  <dbl>   <dbl>  <dbl>   <dbl>   <dbl>    <dbl>   <dbl>
## 1 househol~ 20640  500.   3.82e2  409    3.25e2  280     605       1      6082  
## 2 housing_~ 20640   28.6  1.26e1   29    1.9 e1   18      37       1        52  
## 3 latitude  20640   35.6  2.14e0   34.3  3.78e0   33.9    37.7    32.5      42.0
## 4 longitude 20640 -120.   2.00e0 -118.   3.79e0 -122.   -118.   -124.     -114. 
## 5 median_i~ 20640    3.87 1.90e0    3.53 2.18e0    2.56    4.74    0.500    15.0
## 6 populati~ 20640 1425.   1.13e3 1166    9.38e2  787    1725       3     35682  
## 7 total_be~ 20640  538.   4.19e2  438    3.46e2  297     643.      1      6445  
## 8 total_ro~ 20640 2636.   2.18e3 2127    1.70e3 1448.   3148       2     39320
\end{verbatim}

A modo de ilustración univariada, graficamos el ingreso medio (\texttt{median\_income}) y la edad media de la vivienda (\texttt{housing\_median\_age}), dos variables clave del modelo.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{median\_income))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\FunctionTok{after\_stat}\NormalTok{(density)), }\AttributeTok{binwidth=}\FloatTok{0.5}\NormalTok{, }\AttributeTok{fill=}\StringTok{"\#2ca02c"}\NormalTok{, }\AttributeTok{color=}\StringTok{"white"}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.7}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{color=}\StringTok{"darkgreen"}\NormalTok{, }\AttributeTok{linewidth=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Distribución del Ingreso Medio de los Hogares\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Ingreso Medio (Escala de Decenas de Miles de USD)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Densidad\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/hist_income-1} \end{center}

\textbf{Interpretación del Ingreso Medio:}
La variable \texttt{median\_income} muestra una distribución unimodal sesgada a la derecha. El rango intercuartílico sugiere que la mayor parte de las observaciones se agrupan en ingresos de entre \(\$25,000\) y \(\$65,000\) USD aproximados, con una cola larga hacia valores de ingresos elevados que representan a sectores residenciales de alta renta.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{housing\_median\_age))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\DecValTok{2}\NormalTok{, }\AttributeTok{fill=}\StringTok{"\#9467bd"}\NormalTok{, }\AttributeTok{color=}\StringTok{"white"}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.7}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Distribución de la Edad Media de las Viviendas\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Edad Media de la Vivienda (Años)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Frecuencia\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/hist_age-1} \end{center}

\textbf{Interpretación de la Edad de las Viviendas:}
La variable \texttt{housing\_median\_age} presenta una distribución relativamente uniforme, aunque con ligeros picos y una acumulación notable en el límite superior (cerca de los 52 años), lo que puede representar viviendas históricas o un efecto de truncamiento superior similar al observado en los precios de la vivienda.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{Variable Categórica: Proximidad al Océano (\texttt{ocean\_proximity})}{Variable Categórica: Proximidad al Océano (ocean\_proximity)}}\label{variable-categuxf3rica-proximidad-al-ocuxe9ano-ocean_proximity}

Analizamos la frecuencia relativa de la localización de los bloques con respecto al mar.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_ocean\_b }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(ocean\_proximity,}\AttributeTok{name=}\StringTok{"n"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Porcentaje=}\FunctionTok{round}\NormalTok{((n}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(n))}\SpecialCharTok{*}\DecValTok{100}\NormalTok{,}\DecValTok{1}\NormalTok{),}
         \AttributeTok{Etiqueta=}\FunctionTok{paste0}\NormalTok{(n,}\StringTok{" ("}\NormalTok{,Porcentaje,}\StringTok{"\%)"}\NormalTok{))}

\NormalTok{tabla\_ocean\_b }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(ocean\_proximity, }\SpecialCharTok{{-}}\NormalTok{n), }\AttributeTok{y=}\NormalTok{n, }\AttributeTok{fill=}\NormalTok{ocean\_proximity))}\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{(}\AttributeTok{width =} \FloatTok{0.6}\NormalTok{, }\AttributeTok{show.legend =} \ConstantTok{FALSE}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label=}\NormalTok{Etiqueta), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \DecValTok{4}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Distribución de Frecuencia: Proximidad al Océano\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Proximidad al Océano\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Número de Bloques (Frecuencia)\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{expand =} \FunctionTok{expansion}\NormalTok{(}\AttributeTok{mult =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.15}\NormalTok{)))}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/tabla_ocean-1} \end{center}

\textbf{Interpretación de la Proximidad al Océano:}
La categoría \texttt{\textless{}1H\ OCEAN} (menos de una hora del océano) es la predominante en la muestra con un \(44.3\%\), seguida de \texttt{INLAND} (tierra adentro) con un \(31.7\%\). En contraste, la presencia de observaciones en la categoría \texttt{ISLAND} es marginal (\(5\) observaciones, \(<0.1\%\)), lo que indica una limitación de representatividad estadística para dicho nivel en análisis inferenciales posteriores.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Análisis Bivariado (Independientes vs.~Dependiente)}\label{anuxe1lisis-bivariado-independientes-vs.-dependiente}

\subsection{Gráficos de Dispersión y Relaciones Lineales}\label{gruxe1ficos-de-dispersiuxf3n-y-relaciones-lineales}

Analizamos el comportamiento de la variable dependiente \texttt{median\_house\_value} ante variaciones en los principales predictores numéricos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{median\_income, }\AttributeTok{y=}\NormalTok{median\_house\_value))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.3}\NormalTok{, }\AttributeTok{color=}\StringTok{\textquotesingle{}\#1f77b4\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color=}\StringTok{"\#d62728"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Relación entre Ingreso Medio y Valor de la Vivienda\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Ingreso Medio (Hogares)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Valor Medio de la Vivienda (USD)\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/scatter_income-1} \end{center}

\textbf{Interpretación:}
Existe una correlación lineal positiva y robusta entre el ingreso medio (\texttt{median\_income}) y el valor medio de la vivienda (\texttt{median\_house\_value}). A medida que se incrementa el ingreso en el bloque, el precio medio del inmueble asciende de forma sistemática. La línea de regresión con pendiente positiva ilustra esta asociación. Asimismo, se evidencia la franja superior horizontal sólida en \(\$500,001\) USD debido al truncamiento de datos.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{housing\_median\_age, }\AttributeTok{y=}\NormalTok{median\_house\_value))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.15}\NormalTok{, }\AttributeTok{color=}\StringTok{\textquotesingle{}\#9467bd\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{, }\AttributeTok{color=}\StringTok{"\#d62728"}\NormalTok{, }\AttributeTok{se=}\ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Relación entre Edad de la Vivienda y Valor de la Vivienda\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Edad Media de la Vivienda (Años)\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Valor Medio de la Vivienda (USD)\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/scatter_age-1} \end{center}

\textbf{Interpretación:}
La relación entre \texttt{housing\_median\_age} y \texttt{median\_house\_value} es débilmente positiva. Aunque la pendiente estimada por regresión lineal tiende al alza, existe una dispersión muy amplia en cada nivel de edad, lo que indica que la antigüedad del bloque por sí sola no determina el valor final de la vivienda de forma unívoca, sino que interactúa con otras características del entorno.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Análisis Numérico vs.~Categórico}\label{anuxe1lisis-numuxe9rico-vs.-categuxf3rico}

Evaluamos el comportamiento de \texttt{median\_house\_value} a través de los distintos grupos geográficos de la variable \texttt{ocean\_proximity}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(ocean\_proximity, median\_house\_value, }\AttributeTok{FUN =}\NormalTok{ median), }\AttributeTok{y=}\NormalTok{median\_house\_value, }\AttributeTok{fill=}\NormalTok{ocean\_proximity))}\SpecialCharTok{+}
  \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{show.legend =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{alpha=}\FloatTok{0.8}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=}\StringTok{\textquotesingle{}Distribución del Valor de la Vivienda por Proximidad al Océano\textquotesingle{}}\NormalTok{,}
       \AttributeTok{x=}\StringTok{\textquotesingle{}Proximidad al Océano\textquotesingle{}}\NormalTok{,}
       \AttributeTok{y=}\StringTok{\textquotesingle{}Valor Medio de la Vivienda (USD)\textquotesingle{}}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{palette =} \StringTok{"Set2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{bookdown-demo_files/figure-latex/box_ocean_value-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(ocean\_proximity) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{ (}\AttributeTok{n=}\FunctionTok{length}\NormalTok{(median\_house\_value),}
             \AttributeTok{media=}\FunctionTok{mean}\NormalTok{(median\_house\_value),}
             \AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(median\_house\_value),}
             \AttributeTok{mediana=}\FunctionTok{median}\NormalTok{(median\_house\_value),}
             \AttributeTok{RIC=}\FunctionTok{IQR}\NormalTok{(median\_house\_value),}
             \AttributeTok{q1=}\FunctionTok{quantile}\NormalTok{(median\_house\_value,}\FloatTok{0.25}\NormalTok{),}
             \AttributeTok{q3=}\FunctionTok{quantile}\NormalTok{(median\_house\_value,}\FloatTok{0.75}\NormalTok{),}
             \AttributeTok{minimo=}\FunctionTok{min}\NormalTok{(median\_house\_value),}
             \AttributeTok{maximo=}\FunctionTok{max}\NormalTok{(median\_house\_value)) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 10
##   ocean_proximity     n  media     sd mediana    RIC     q1     q3 minimo maximo
##   <fct>           <int>  <dbl>  <dbl>   <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
## 1 <1H OCEAN        9136 2.40e5 1.06e5  214850 125000 164100 289100  17500 500001
## 2 INLAND           6551 1.25e5 7.00e4  108500  71450  77500 148950  14999 500001
## 3 ISLAND              5 3.80e5 8.06e4  414700 150000 300000 450000 287500 450000
## 4 NEAR BAY         2290 2.59e5 1.23e5  233800 183200 162500 345700  22500 500001
## 5 NEAR OCEAN       2658 2.49e5 1.22e5  229450 172750 150000 322750  22500 500001
\end{verbatim}

\textbf{Interpretación:}
El análisis de distribución segmentado revela que las viviendas localizadas a menos de una hora del océano (\texttt{\textless{}1H\ OCEAN}), en bahías (\texttt{NEAR\ BAY}) o directamente frente al mar (\texttt{NEAR\ OCEAN}) ostentan medianas y promedios significativamente más elevados que aquellas clasificadas como de tierra adentro (\texttt{INLAND}). La categoría \texttt{ISLAND} cuenta con los valores más elevados, pero su escaso número muestral limita generalizaciones fiables. Este resultado preliminar valida la hipótesis de que la localización geográfica y la cercanía costera introducen una prima sustancial sobre el costo de la propiedad.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Análisis de Colinealidad y Matriz de Correlación}\label{anuxe1lisis-de-colinealidad-y-matriz-de-correlaciuxf3n}

Para identificar posibles relaciones y colinealidad entre todas las variables continuas del modelo:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Para evitar sobrecargar la compilación, se puede evaluar la correlación global}
\CommentTok{\# y graficar la matriz de correlación directamente.}
\NormalTok{df\_numeric }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.numeric))}
\NormalTok{cor\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(df\_numeric, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\FunctionTok{round}\NormalTok{(cor\_matrix, }\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    longitude latitude housing_median_age total_rooms
## longitude               1.00    -0.92              -0.11        0.04
## latitude               -0.92     1.00               0.01       -0.04
## housing_median_age     -0.11     0.01               1.00       -0.36
## total_rooms             0.04    -0.04              -0.36        1.00
## total_bedrooms          0.07    -0.07              -0.32        0.93
## population              0.10    -0.11              -0.30        0.86
## households              0.06    -0.07              -0.30        0.92
## median_income          -0.02    -0.08              -0.12        0.20
## median_house_value     -0.05    -0.14               0.11        0.13
##                    total_bedrooms population households median_income
## longitude                    0.07       0.10       0.06         -0.02
## latitude                    -0.07      -0.11      -0.07         -0.08
## housing_median_age          -0.32      -0.30      -0.30         -0.12
## total_rooms                  0.93       0.86       0.92          0.20
## total_bedrooms               1.00       0.87       0.97         -0.01
## population                   0.87       1.00       0.91          0.00
## households                   0.97       0.91       1.00          0.01
## median_income               -0.01       0.00       0.01          1.00
## median_house_value           0.05      -0.02       0.07          0.69
##                    median_house_value
## longitude                       -0.05
## latitude                        -0.14
## housing_median_age               0.11
## total_rooms                      0.13
## total_bedrooms                   0.05
## population                      -0.02
## households                       0.07
## median_income                    0.69
## median_house_value               1.00
\end{verbatim}

Para almacenar la matriz de dispersión visual completa de alta resolución:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{png}\NormalTok{(}\StringTok{"mi\_grafico.png"}\NormalTok{, }\AttributeTok{width =} \DecValTok{4800}\NormalTok{, }\AttributeTok{height =} \DecValTok{4000}\NormalTok{, }\AttributeTok{res =} \DecValTok{300}\NormalTok{)}
\NormalTok{df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{ggpairs}\NormalTok{()}
\FunctionTok{dev.off}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## pdf 
##   2
\end{verbatim}

\chapter{Introduction}\label{intro}

You can label chapter and section titles using \texttt{\{\#label\}} after them, e.g., we can reference Chapter \ref{intro}. If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \ref{methods}.

Figures and tables with captions will be placed in \texttt{figure} and \texttt{table} environments, respectively.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mar =} \FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{4}\NormalTok{, .}\DecValTok{1}\NormalTok{, .}\DecValTok{1}\NormalTok{))}
\FunctionTok{plot}\NormalTok{(pressure, }\AttributeTok{type =} \StringTok{\textquotesingle{}b\textquotesingle{}}\NormalTok{, }\AttributeTok{pch =} \DecValTok{19}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{bookdown-demo_files/figure-latex/nice-fig-1} 

}

\caption{Here is a nice figure!}\label{fig:nice-fig}
\end{figure}

Reference a figure by its code chunk label with the \texttt{fig:} prefix, e.g., see Figure \ref{fig:nice-fig}. Similarly, you can reference tables generated from \texttt{knitr::kable()}, e.g., see Table \ref{tab:nice-tab}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
  \FunctionTok{head}\NormalTok{(iris, }\DecValTok{20}\NormalTok{), }\AttributeTok{caption =} \StringTok{\textquotesingle{}Here is a nice table!\textquotesingle{}}\NormalTok{,}
  \AttributeTok{booktabs =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{\label{tab:nice-tab}Here is a nice table!}
\centering
\begin{tabular}[t]{rrrrl}
\toprule
Sepal.Length & Sepal.Width & Petal.Length & Petal.Width & Species\\
\midrule
5.1 & 3.5 & 1.4 & 0.2 & setosa\\
4.9 & 3.0 & 1.4 & 0.2 & setosa\\
4.7 & 3.2 & 1.3 & 0.2 & setosa\\
4.6 & 3.1 & 1.5 & 0.2 & setosa\\
5.0 & 3.6 & 1.4 & 0.2 & setosa\\
\addlinespace
5.4 & 3.9 & 1.7 & 0.4 & setosa\\
4.6 & 3.4 & 1.4 & 0.3 & setosa\\
5.0 & 3.4 & 1.5 & 0.2 & setosa\\
4.4 & 2.9 & 1.4 & 0.2 & setosa\\
4.9 & 3.1 & 1.5 & 0.1 & setosa\\
\addlinespace
5.4 & 3.7 & 1.5 & 0.2 & setosa\\
4.8 & 3.4 & 1.6 & 0.2 & setosa\\
4.8 & 3.0 & 1.4 & 0.1 & setosa\\
4.3 & 3.0 & 1.1 & 0.1 & setosa\\
5.8 & 4.0 & 1.2 & 0.2 & setosa\\
\addlinespace
5.7 & 4.4 & 1.5 & 0.4 & setosa\\
5.4 & 3.9 & 1.3 & 0.4 & setosa\\
5.1 & 3.5 & 1.4 & 0.3 & setosa\\
5.7 & 3.8 & 1.7 & 0.3 & setosa\\
5.1 & 3.8 & 1.5 & 0.3 & setosa\\
\bottomrule
\end{tabular}
\end{table}

You can write citations, too. For example, we are using the \textbf{bookdown} package \citep{R-bookdown} in this sample book, which was built on top of R Markdown and \textbf{knitr} \citep{xie2015}.

\chapter{Literature}\label{literature}

Here is a review of existing methods.

\chapter{Methods}\label{methods}

We describe our methods in this chapter.

Math can be added in body using usual syntax like this

\section{math example}\label{math-example}

\(p\) is unknown but expected to be around 1/3. Standard error will be approximated

\[
SE = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
\]

You can also use math in footnotes like this\footnote{where we mention \(p = \frac{a}{b}\)}.

We will approximate standard error to 0.027\footnote{\(p\) is unknown but expected to be around 1/3. Standard error will be approximated

  \[
  SE = \sqrt{\frac{p(1-p)}{n}} \approx \sqrt{\frac{1/3 (1 - 1/3)} {300}} = 0.027
  \]}

\chapter{Applications}\label{applications}

Some \emph{significant} applications are demonstrated in this chapter.

\section{Example one}\label{example-one}

\section{Example two}\label{example-two}

\chapter{Final Words}\label{final-words}

We have finished a nice book.

\bibliography{book.bib,packages.bib}

\end{document}
